# Generated by Django 3.1.2 on 2021-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='doses',
            field=models.PositiveIntegerField(choices=[(1, 'première dose'), (2, 'deuxieme dose')], max_length=2),
        ),
    ]
