# Generated by Django 3.1.2 on 2021-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_auto_20210217_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qrcodes/'),
        ),
    ]
