# Generated by Django 3.1.2 on 2021-02-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_auto_20210217_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='centre_vaccination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre', to='vaccination.centrevaccination'),
        ),
    ]
